export const COURSES =
[
  {
    watched: 6,
    rank: 0,
    like: 1,
    dislike: 0,
    favoriteCount: 0,
    duration: 'PT4M25S',
    commentCount: 0,
    slug: 'restore-your-mac-with-qnap-nas-and-timemachine-backup',
    slide_link: '',
    comments: [],
    _id: '5d781c789094120ba1ce8703',
    title: 'Restore your Mac with QNAP NAS and TimeMachine Backup',
    code_name: 'QNP217',
    youtube_ref: 'Gief3_v8XOg',
    category: 'sophomore',
    desc: 'Restore your Mac with QNAP NAS and TimeMachine Backup',
    keywords: 'Apple,OSX,Backup,Restore',
    publishedDate: '2019-09-11T20:44:19.000Z',
    __v: 0
  },
  {
    watched: 16,
    rank: 0,
    like: 1,
    dislike: 0,
    favoriteCount: 0,
    duration: 'PT2M28S',
    commentCount: 0,
    slug: 'manually-install-qnap-app',
    slide_link: '',
    comments: [],
    _id: '5d781ab69094120ba1ce86f8',
    title: 'Manually Install QNAP App ',
    code_name: 'QNP171',
    youtube_ref: 'R5QdvWrS2RU',
    category: 'freshman',
    desc: 'This tutorial will demonstrate how to install QNAP App manually',
    keywords: 'App Center',
    publishedDate: '2019-09-11T20:40:19.000Z',
    __v: 0
  },
  {
    watched: 229,
    rank: 0,
    like: 7,
    dislike: 0,
    favoriteCount: 0,
    duration: 'PT12M21S',
    commentCount: 0,
    slug: 'hybridmount:-access-public-cloud-at-lan-speeds',
    slide_link: 'https://www.slideshare.net/QNAP_Inc/hybridmount-access-public-cloud-at-lan-speeds-169125692',
    comments: [],
    _id: '5d7819539094120ba1ce86f4',
    title: 'HybridMount: Access Public Cloud at LAN Speeds',
    code_name: 'Webinar15',
    youtube_ref: 'NoQ642wYR-A',
    category: 'webinar',
    desc: 'Access your public cloud at local speeds with QNAP\'s Hybrid Mount.',
    keywords: 'Private Cloud',
    publishedDate: '2019-09-04T23:39:30.000Z',
    __v: 0
  },
  {
    watched: 209,
    rank: 0,
    like: 15,
    dislike: 0,
    favoriteCount: 0,
    duration: 'PT6M30S',
    commentCount: 1,
    slug: 'qsync-central-your-private-dropbox',
    slide_link: '',
    comments: [],
    _id: '5d54aac78c76f32126491c74',
    title: 'Qsync Central - Your Private Dropbox',
    code_name: 'QNP354',
    youtube_ref: 'MqcFpcr41t0',
    category: 'junior',
    desc: 'This Tutorial will go over how to sync a shared folder across devices using your QNAP NAS with the app, Qsync Central.',
    keywords: 'sync,qsync,file sharing,collaboration,Dropbox',
    publishedDate: '2019-08-14T23:51:57.000Z',
    __v: 0
  },
  {
    watched: 565,
    rank: 0,
    like: 10,
    dislike: 2,
    favoriteCount: 0,
    duration: 'PT24M4S',
    commentCount: 4,
    slug: 'hybrid-backup-sync-3.0:-backup-with-dedup-for-faster-speed-and-less-space',
    // tslint:disable-next-line: max-line-length
    slide_link: 'https://www.slideshare.net/QNAP_Inc/hybrid-backup-sync-30-backup-with-deduplication-for-faster-speed-and-less-space?qid=40423b99-8e3e-42ee-9f89-c0fc1b4c42e2&v=&b=&from_search=2',
    comments: [],
    _id: '5d407c0513c02c03b5beb7e1',
    publishedDate: '2019-07-30T17:15:58.000Z',
    keywords: 'QuDedup,HBS,HBS3',
    desc: 'Backup with confidence with HBS3 + Qudedup + Multi-versioning',
    category: 'webinar',
    youtube_ref: '77UsvwV0VNc',
    code_name: 'Webinar14',
    title: 'Hybrid Backup Sync 3.0: Backup with Dedup for Faster Speed and Less Space',
    __v: 0
  },
  {
    watched: 306,
    rank: 0,
    like: 5,
    dislike: 0,
    favoriteCount: 0,
    duration: 'PT2M16S',
    commentCount: 0,
    slug: 'configuring-permission-for-a-shared-folder-on-qnap-nas',
    slide_link: '',
    comments: [],
    _id: '5d126f5aafb79941a504d4a1',
    publishedDate: '2019-06-25T18:04:56.000Z',
    keywords: 'permissions,shared folder,data security',
    desc: 'This tutorial will describe how to set varying user permissions for shared folders.',
    category: 'freshman',
    youtube_ref: 'vD_hziwGfo8',
    code_name: 'QNP123',
    title: 'Configuring Permission for a Shared Folder on QNAP NAS',
    __v: 0
  },
  {
    watched: 307,
    rank: 0,
    like: 8,
    dislike: 1,
    favoriteCount: 0,
    duration: 'PT19M20S',
    commentCount: 0,
    slug: 'notification-center:-stay-informed-of-your-nas-status-at-all-times',
    slide_link: 'https://www.slideshare.net/QNAP_Inc/notification-center',
    comments: [
        '5d124fdcafb79941a504d484'
    ],
    _id: '5cf6aa0f7b38191f6ee39e2e',
    publishedDate: '2019-05-28T18:42:54.000Z',
    keywords: 'Notification Center',
    desc: 'The walk through for the feature - Notification Center',
    category: 'webinar',
    youtube_ref: 'RlDqO3xQ5pY',
    code_name: 'Webinar13',
    title: 'Notification Center: Stay informed of your NAS status at all times',
    __v: 1
  },
  {
    id: 8,
    watched: 569,
    rank: 0,
    like: 9,
    dislike: 0,
    favoriteCount: 0,
    duration: 'PT1M40S',
    commentCount: 0,
    slug: 'how-to-convert-a-thick-volume-to-a-thin-volume',
    slide_link: '',
    comments: [],
    _id: '5cdf505789b0a25980f7adef',
    publishedDate: '2019-05-18T00:17:26.000Z',
    keywords: 'Thick Volume,Thin Volume,QTS,Initialization',
    // tslint:disable-next-line: max-line-length
    desc: 'This tutorial will describe the difference between a thick volume and a thin volume and will show you how to convert a thick volume to a thin volume.',
    category: 'sophomore',
    youtube_ref: 'qUqQk8nB248',
    code_name: 'QNP229',
    title: 'How to Convert a Thick Volume to a Thin Volume',
    __v: 0
  },
  {
    id: 9,
    watched: 213,
    rank: 0,
    like: 9,
    dislike: 0,
    favoriteCount: 0,
    duration: 'PT3M20S',
    commentCount: 1,
    slug: 'qvr-pro-guide-how-to-dewarp-a-camera-view',
    slide_link: '',
    comments: [],
    _id: '5cdf4cb389b0a25980f7ade3',
    publishedDate: '2019-05-18T00:04:20.000Z',
    keywords: 'QVR Pro,dewarp,surveillance',
    desc: 'This tutorial will show you how to dewarp your camera view in QVR Pro.',
    category: 'sophomore',
    youtube_ref: 'w10QTV7rWjU',
    code_name: 'QNP233',
    title: 'QVR Pro Guide - How to Dewarp a Camera View',
    __v: 0
  },
  {
      watched: 493,
      rank: 0,
      like: 10,
      dislike: 1,
      favoriteCount: 0,
      duration: 'PT10M2S',
      commentCount: 3,
      slug: 'virtualization-station-3.2:-enhanced-with-pcie-passthrough',
      slide_link: 'https://www.slideshare.net/QNAP_Inc/virtualization-station-32-ppt-from-webinar',
      comments: [],
      _id: '5cd1be4e89b0a25980f7ac71',
      publishedDate: '2019-04-24T23:35:35.000Z',
      keywords: 'Virtualization Station,PCIe Passthrough',
      desc: 'New Virtualization Station enhanced with PCIe Passthrough',
      category: 'webinar',
      youtube_ref: 'UIjOQNsWkNg',
      code_name: 'Webinar12',
      title: 'Virtualization Station 3.2: Enhanced with PCIe Passthrough',
      __v: 0
  },
  {
      watched: 1764,
      rank: 0,
      like: 17,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT6M47S',
      commentCount: 1,
      slug: 'setting-up-your-qnap-nas-as-a-roon-server',
      slide_link: '',
      comments: [],
      _id: '5ca284b189b0a25980f7a89d',
      publishedDate: '2019-04-01T21:36:09.000Z',
      keywords: 'Roon,Music,streaming',
      // tslint:disable-next-line:max-line-length
      desc: 'This video illustrates how to setup your QNAP NAS as a Roon server and then yuo can use Roon client app to listen the streaming music from QNAP NAS.',
      category: 'sophomore',
      youtube_ref: 'aJG_7THuSTw',
      code_name: 'QNP235',
      title: 'Setting Up Your QNAP NAS as a Roon Server',
      __v: 0
  },
  {
      watched: 321,
      rank: 0,
      like: 2,
      dislike: 1,
      favoriteCount: 0,
      duration: 'PT1M24S',
      commentCount: 0,
      slug: 'how-to-set-a-reset-password-policy',
      slide_link: '',
      comments: [
          '5c67366aedf5be4dd883832e'
      ],
      _id: '5c630f8732b756384e7e9b74',
      publishedDate: '2019-02-07T23:43:20.000Z',
      keywords: 'Password,Password reset',
      desc: 'This video teaches how to setup a reset password policy.',
      category: 'freshman',
      youtube_ref: 'j-Yw0Rfmfwk',
      code_name: 'QNP170',
      title: 'How to Set a Reset Password Policy',
      __v: 1
  },
  {
      watched: 3184,
      rank: 0,
      like: 42,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT18M44S',
      commentCount: 1,
      slug: 'secure-remote-access-to-your-network-through-qvpn',
      slide_link: 'https://www.slideshare.net/QNAP_Inc/slides-for-vpn-webinar3',
      comments: [
          '5c675c72edf5be4dd88383eb'
      ],
      _id: '5c50b9ccf02b7713a44ce828',
      publishedDate: '2019-01-29T20:38:21.000Z',
      keywords: 'QVPN,QBelt,PPTP,OpenVPN,L2TP',
      desc: 'New features about QVPN service.',
      category: 'webinar',
      youtube_ref: 'T2CEMdqfZ-c',
      code_name: 'Webinar11',
      title: 'Secure Remote Access to Your Network Through QVPN',
      __v: 1
  },
  {
      watched: 364,
      rank: 0,
      like: 5,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT2M24S',
      commentCount: 1,
      slug: 'qvr-pro-guide-how-to-setup-e-maps',
      slide_link: '',
      comments: [],
      _id: '5c4bb79e9752474e135925f4',
      publishedDate: '2019-01-26T01:25:37.000Z',
      keywords: 'QVR Pro,E-Map',
      desc: 'This video will show you how to setup a e-map for better surveillance experience\n',
      category: 'junior',
      youtube_ref: 'x_gzk_ZR3xE',
      code_name: 'QNP353',
      title: 'QVR Pro Guide - How To Setup E-maps',
      __v: 0
  },
  {
      watched: 631,
      rank: 0,
      like: 10,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT2M28S',
      commentCount: 0,
      slug: 'how-to-setup-static-route',
      slide_link: '',
      comments: [],
      _id: '5c48c2f29752474e13592596',
      publishedDate: '2019-01-23T19:37:30.000Z',
      keywords: 'Static Route,Network Virtual Switch',
      desc: 'QTS 4.3.5 supports static route, and this video illustrates how to setup the static route',
      category: 'junior',
      youtube_ref: 'qe0FSfeqVpE',
      code_name: 'QNP352',
      title: 'How to Setup Static Route',
      __v: 0
  },
  {
      watched: 1455,
      rank: 0,
      like: 11,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT4M26S',
      commentCount: 7,
      slug: 'how-to-setup-motion-detection',
      slide_link: '',
      comments: [],
      _id: '5c0b0f2b9752474e13591e56',
      publishedDate: '2018-12-08T00:21:47.000Z',
      keywords: 'QVR Pro,Motion Detection,IP Camera',
      desc: 'This tutorial illustrates how to setup motion detection for event recording in QVR Pro.',
      category: 'junior',
      youtube_ref: 'eMLY2uXYM1g',
      code_name: 'QNP351',
      title: 'How to Setup Motion Detection',
      __v: 0
  },
  {
      watched: 725,
      rank: 0,
      like: 10,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT22M39S',
      commentCount: 3,
      slug: 'everything-you-should-know-about-qnap-snapshot',
      slide_link: '',
      comments: [],
      _id: '5be61b1b610dbf576488ad31',
      publishedDate: '2018-11-09T22:58:28.000Z',
      keywords: 'snapshot,qtier,provisioning,storage manager,QTS 4.3.5',
      desc: 'Explain everything you need to know about QNAP Snapshot & Snapshot Replica',
      category: 'webinar',
      youtube_ref: 'wR-lzpYVRmQ',
      code_name: 'Webinar10',
      title: 'Everything You Should Know About QNAP Snapshot',
      __v: 0
  },
  {
      watched: 398,
      rank: 0,
      like: 4,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT5M33S',
      commentCount: 1,
      slug: 'how-to-add-a-nas-behind-the-nat-into-q\'center-server',
      slide_link: '',
      comments: [
          '5ca536f089b0a25980f7a8ed'
      ],
      _id: '5bd38b61610dbf576488abcd',
      publishedDate: '2018-10-26T21:43:56.000Z',
      keywords: 'Q\'center,Qcenter,NAT,Firewall,Central Management',
      // tslint:disable-next-line: max-line-length
      desc: 'Add a NAS into Q\'Center is always straight forward.  However, adding a NAS behind a NAT is not.  This tutorial tells you how to add a NAS behind the NAT',
      category: 'senior',
      youtube_ref: 'LE-pcQA4RKU',
      code_name: 'QNP441',
      title: 'How to Add a NAS Behind the NAT into Q\'Center Server',
      __v: 1
  },
  {
      watched: 699,
      rank: 0,
      like: 8,
      dislike: 2,
      favoriteCount: 0,
      duration: 'PT20M53S',
      commentCount: 0,
      slug: 'boost-performance-with-qnap-software-defined-external-ssd-over-provisioning',
      slide_link: 'https://www.slideshare.net/QNAP_Inc/boost-performance-with-software-defined-ssd-overprovisioning',
      comments: [],
      _id: '5bbb9d29610dbf576488a9e7',
      publishedDate: '2018-10-08T18:05:37.000Z',
      keywords: 'SSD,OP,Over-provisioning',
      // tslint:disable-next-line: max-line-length
      desc: 'With falling SSD prices and the additional OP configuration in QTS 4.3.5, the time is right for business and home users to consider adding SSDs to their QNAP NAS. ',
      category: 'webinar',
      youtube_ref: 'cN9dHFBrfuo',
      code_name: 'Webinar6',
      title: 'Boost Performance with QNAP Software-defined External SSD Over-provisioning',
      __v: 0
  },
  {
      watched: 288,
      rank: 0,
      like: 6,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT3M40S',
      commentCount: 0,
      slug: 'qvr-pro-guide-batch-import-cameras',
      slide_link: '',
      comments: [],
      _id: '5bac0dd56043145fed6990b7',
      publishedDate: '2018-09-26T21:40:59.000Z',
      keywords: 'import,QVR Pro,Vivotek',
      desc: 'This QVR Pro serise Batch Import Cameras teaches you how to add cameras into QVR Pro in batch.',
      category: 'junior',
      youtube_ref: 'kMRcfDsrHlM',
      code_name: 'QNP350',
      title: 'QVR Pro Guide - Batch Import Cameras',
      __v: 0
  },
  {
      watched: 596,
      rank: 0,
      like: 8,
      dislike: 1,
      favoriteCount: 0,
      duration: 'PT29M16S',
      commentCount: 0,
      slug: 'overview-of-qts-4-3-5-networking-enhanced-network-management',
      slide_link: 'https://www.slideshare.net/QNAP_Inc/networking-enhanced-network-management',
      comments: [],
      _id: '5baa7cb96043145fed699098',
      publishedDate: '2018-09-25T17:38:04.000Z',
      keywords: 'Virtual Switch,QTS 4.3.5,static route,IPV6,RADVD,topology',
      // tslint:disable-next-line: max-line-length
      desc: 'The improved Network & Virtual Switch app boosts interoperability between QNAP NAS, containers, virtual machines, and other devices.',
      category: 'webinar',
      youtube_ref: 'XFzwoybhXKs',
      code_name: 'Webinar5',
      title: 'Overview of QTS 4 3 5 networking Enhanced Network Management',
      __v: 0
  },
  {
      watched: 5337,
      rank: 0,
      like: 46,
      dislike: 1,
      favoriteCount: 0,
      duration: 'PT44M7S',
      commentCount: 7,
      slug: 'a-complete-guide-to-qnap-storage-management',
      slide_link: 'https://www.slideshare.net/QNAP_Inc/complete-guide-to-storage-management',
      comments: [],
      _id: '5b5105d1e449ca649bbc1675',
      publishedDate: '2018-07-19T21:10:17.000Z',
      keywords: 'Qtier,Storage Manager,SSD Cache',
      desc: 'The guide to walk you through the whole interface of QNAP\s storage management',
      category: 'webinar',
      youtube_ref: '-zhVkfun3Hk',
      code_name: 'Webinar4',
      title: 'A Complete Guide to QNAP Storage Management',
      __v: 0
  },
  {
      watched: 753,
      rank: 0,
      like: 7,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT45M5S',
      commentCount: 1,
      slug: 'tackle-performance-bottlenecks-with-new-qnap-qm2-expansion-cards',
      slide_link: 'https://www.slideshare.net/QNAP_Inc/tackle-performance-bottlenecks-with-new-qnap-qm2-expansion-cards',
      comments: [],
      _id: '5b23fd946a5b9f239dc93155',
      publishedDate: '2018-06-15T17:46:16.000Z',
      keywords: 'NVMe,QM2,Expansion',
      desc: 'Upgrade your network environment for better performance, collaboration, and more potential applications',
      category: 'webinar',
      youtube_ref: 'hVTqBBOMl3k',
      code_name: 'Webinar3',
      title: 'Tackle performance bottlenecks with new QNAP QM2 Expansion cards',
      __v: 0
  },
  {
      watched: 10671,
      rank: 0,
      like: 35,
      dislike: 4,
      favoriteCount: 0,
      duration: 'PT3M37S',
      commentCount: 7,
      slug: 'backup-data-from-other-nas-to-qnap-nas',
      slide_link: '',
      comments: [],
      _id: '5afe13d80e999d3092db7aac',
      keywords: 'synology,buffalo,netgear,drobo',
      desc: 'This video demonstrates how to transfer your data from other brand of NAS to QNAP NAS',
      category: 'Junior',
      youtube_ref: 'lDb0AwHnfHI',
      code_name: 'QNP341',
      title: 'Backup data from other NAS to QNAP NAS',
      __v: 0,
      publishedDate: '2018-05-02T19:31:04.000Z'
  },
  {
      watched: 12341,
      rank: 0,
      like: 54,
      dislike: 2,
      favoriteCount: 0,
      duration: 'PT4M41S',
      commentCount: 5,
      slug: 'backup-your-photos-on-your-phone-to-qnap-nas',
      slide_link: '',
      comments: [],
      _id: '5afe02b9b729a72bbb88a34a',
      keywords: 'iphone,android,mobile',
      desc: 'This video demonstrates how to backup your file through Qfile, and also setup auto uploading.',
      category: 'junior',
      youtube_ref: 'VR8y472MYgc',
      code_name: 'QNP340',
      title: 'Backup Your Photos on Your Phone to QNAP NAS',
      __v: 0,
      publishedDate: '2018-05-01T18:29:50.000Z'
  },
  {
      watched: 2080,
      rank: 0,
      like: 13,
      dislike: 2,
      favoriteCount: 0,
      duration: 'PT23M55S',
      commentCount: 3,
      slug: 'qvr-pro-a-professional-nvr-solution-for-nas',
      slide_link: 'https://www.slideshare.net/QNAP_Inc/qvr-pro-a-professional-nvr-solution-for-nas',
      comments: [],
      _id: '5afe11d60e999d3092db7aaa',
      keywords: 'Surveillance,camera,VMS',
      desc: 'QVR Pro allows you to create an independent and expandable surveillance environment on your NAS.',
      category: 'webinar',
      youtube_ref: 'yd5y5srRyIU',
      code_name: 'Webinar2',
      title: 'QVR Pro - A Professional NVR Solution for NAS',
      __v: 0,
      publishedDate: '2018-04-04T18:06:11.000Z'
  },
  {
      watched: 4625,
      rank: 0,
      like: 14,
      dislike: 3,
      favoriteCount: 0,
      duration: 'PT18M4S',
      commentCount: 5,
      slug: 'ultimate-mail-client-on-private-cloud-qmailagent-and-qmailclient',
      slide_link: 'https://www.slideshare.net/QNAP_Inc/ultimate-mail-client-on-private-cloud-qmailagent-qmailclient',
      comments: [],
      _id: '5afe13280e999d3092db7aab',
      keywords: 'gmail,hotmail,outlook',
      desc: 'Everything about Ultimate Mail Client on Private Cloud – QmailAgent & QmailClient',
      category: 'webinar',
      youtube_ref: '63U9a1hfppc',
      code_name: 'Webinar1',
      title: 'Ultimate Mail Client on Private Cloud – QmailAgent & QmailClient',
      __v: 0,
      publishedDate: '2018-01-25T01:57:40.000Z'
  },
  {
      watched: 5012,
      rank: 0,
      like: 22,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT2M31S',
      commentCount: 0,
      slug: 'backup-your-files-from-a-usbexternal-drive',
      slide_link: '',
      comments: [],
      _id: '5afbb4090e52c12ad6bd7b36',
      keywords: 'Backup,One touch copy,file station',
      desc: 'Backup your files from a USB/External drive',
      category: 'junior',
      youtube_ref: 'IyQhoNhlU1M',
      code_name: 'QNP331',
      title: 'Backup your files from a USB/External drive',
      __v: 0,
      publishedDate: '2017-12-15T02:09:47.000Z'
  },
  {
      watched: 1819,
      rank: 0,
      like: 6,
      dislike: 1,
      favoriteCount: 0,
      duration: 'PT1M51S',
      commentCount: 1,
      slug: 'setup-qnap-mobile-apps-with-myqnapcloud-service',
      slide_link: '',
      comments: [],
      _id: '5af9ade651382c874afe4552',
      code_name: 'QNP339',
      desc: 'Initial setup of QNAP mobile apps with myQNAPCloud service.  Access your DATA on QNAP NAS with ease.',
      category: 'junior',
      youtube_ref: '3LEwGcVpX_w',
      title: 'Setup QNAP mobile apps with myQNAPCloud service',
      __v: 0,
      publishedDate: '2017-12-15T01:23:24.000Z',
      keywords: 'cloud,iphone,android'
  },
  {
      watched: 682,
      rank: 0,
      like: 7,
      dislike: 1,
      favoriteCount: 0,
      duration: 'PT3M30S',
      commentCount: 0,
      slug: 'schedule-a-snapshot',
      slide_link: '',
      comments: [],
      _id: '5d7837169094120ba1ce8726',
      title: 'Schedule a Snapshot',
      code_name: 'QNP306',
      youtube_ref: 't7YDmMn2kpI',
      category: 'junior',
      desc: 'This video will cover how to schedule a snapshot taking and explain what system\'s behavior is when storage is full\n',
      keywords: 'Snapshot',
      publishedDate: '2017-12-02T01:09:37.000Z',
      __v: 0
  },
  {
      watched: 14054,
      rank: 0,
      like: 34,
      dislike: 7,
      favoriteCount: 0,
      duration: 'PT3M23S',
      commentCount: 5,
      slug: 'how-to-share-files-with-qnap-nas',
      slide_link: '',
      comments: [],
      _id: '5b7d93296043145fed698e0f',
      publishedDate: '2017-12-02T00:06:56.000Z',
      keywords: 'Email,social network,share link',
      desc: 'This video will go over on how to share files from File Station, and create share links.',
      category: 'sophomore',
      youtube_ref: '4dN7_1UX2Mc',
      code_name: 'QNP225',
      title: 'How to Share Files with QNAP NAS',
      __v: 0
  },
  {
      watched: 4954,
      rank: 0,
      like: 11,
      dislike: 3,
      favoriteCount: 0,
      duration: 'PT2M39S',
      commentCount: 2,
      slug: 'manually-firmware-update',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdcf6',
      title: 'Manually Firmware Update ',
      code_name: 'QNP165',
      desc: 'This video will cover how to manually update the firmware while the internet is not available for NAS.',
      keywords: 'upgrade,auto update',
      youtube_ref: 'cHI-br3lgWs',
      publishedDate: '2017-12-01T00:09:47.000Z',
      category: 'freshman'
  },
  {
      watched: 9738,
      rank: 0,
      like: 47,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT2M58S',
      commentCount: 5,
      slug: 'setup-cache-to-accelerate-storage-performance',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdd0d',
      title: 'Setup Cache to Accelerate Storage Performance',
      code_name: 'QNP303',
      desc: 'This video will illustrates how to enable cache to accelerate storage performance with SSDs.',
      keywords: 'performance,iops,enterprise,acceleration,smb',
      youtube_ref: '7CzqfqzRMw0',
      category: 'junior',
      publishedDate: '2017-11-16T01:19:45.000Z'
  },
  {
      watched: 768,
      rank: 0,
      like: 3,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT1M54S',
      commentCount: 0,
      slug: 'take-a-snapshot-manually',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdd0b',
      title: 'Take a Snapshot manually',
      code_name: 'QNP305',
      desc: 'Manually take a snapshot on QNAP NAS',
      keywords: 'schedule,backup,redundency,Hybrid Backup Sync,disaster recovery',
      youtube_ref: 'Uu-549zBZ3Y',
      category: 'junior',
      publishedDate: '2017-11-08T18:39:41.000Z'
  },
  {
      watched: 6124,
      rank: 0,
      like: 34,
      dislike: 1,
      favoriteCount: 0,
      duration: 'PT4M23S',
      commentCount: 0,
      slug: 'how-to-create-a-qtier-storage',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdd0e',
      title: 'How to Create a Qtier Storage',
      code_name: 'QNP431',
      desc: 'This video illustrate the idea and concept of Qtier, and also demo how to create a Qtier storage with simple steps.',
      keywords: 'tiering,snapshot,thin,provisioning,thick,storage manager',
      youtube_ref: '3bJR8FzRYlw',
      category: 'senior',
      publishedDate: '2017-11-01T19:33:05.000Z'
  },
  {
      watched: 9223,
      rank: 0,
      like: 24,
      dislike: 3,
      favoriteCount: 0,
      duration: 'PT4M28S',
      commentCount: 2,
      slug: 'how-to-join-windows-active-directory',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdd0c',
      title: 'How to Join Windows Active Directory',
      code_name: 'QNP311',
      desc: 'This tutorial illustrates how to join Windows Active Directory',
      keywords: 'AD,LDAP,Domain,Controller,user,management,business,enterprise',
      youtube_ref: 'KFvAGWVRqMs',
      category: 'junior',
      publishedDate: '2017-10-19T17:07:20.000Z'
  },
  {
      watched: 4755,
      rank: 0,
      like: 24,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT7M30S',
      commentCount: 2,
      slug: 'how-to-create-an-encrypted-volume',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdd05',
      title: 'How to create an encrypted volume ',
      code_name: 'QNP218',
      desc: 'This video will teach you how to encrypt your data and how to lock or unlock your volume.',
      keywords: 'encryption,security,secure,storage manager',
      youtube_ref: '_RxTtxk5SKI',
      category: 'sophomore',
      publishedDate: '2017-10-05T21:51:10.000Z'
  },
  {
      watched: 1824,
      rank: 0,
      like: 20,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT4M21S',
      commentCount: 5,
      slug: 'backup-your-data-to-the-public-cloud',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdd0a',
      title: 'Backup Your Data to the Public Cloud',
      code_name: 'QNP333',
      desc: 'This video will use Hybrid Backup Sync to backup from one NAS to a public cloud.',
      keywords: 'Hybrid Backup Sync,Public Cloud,disaster recovery',
      youtube_ref: 'b-boUKDRyPI',
      category: 'junior',
      publishedDate: '2017-10-02T16:57:43.000Z'
  },
  {
      watched: 15784,
      rank: 0,
      like: 65,
      dislike: 4,
      favoriteCount: 0,
      duration: 'PT3M55S',
      commentCount: 12,
      slug: 'backup-your-data-to-another-qnap',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdd09',
      title: 'Backup Your Data to Another QNAP',
      code_name: 'QNP332',
      desc: 'Use Hybrid Backup Sync to backup your local NAS to a remote NAS.',
      keywords: 'Hybrid Backup Sync,disaster recovery',
      youtube_ref: 'gsluYwZjkiU',
      category: 'junior',
      publishedDate: '2017-10-02T16:57:03.000Z'
  },
  {
      watched: 43474,
      rank: 0,
      like: 146,
      dislike: 18,
      favoriteCount: 0,
      duration: 'PT3M49S',
      commentCount: 39,
      slug: 'how-to-upgrade-to-larger-drives-on-qnap-nas',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdd08',
      title: 'How to upgrade to larger drives on QNAP NAS',
      code_name: 'QNP222',
      desc: 'This video will show how to upgrade to larger drives (moving the same data from a smaller drive to a larger)',
      keywords: 'migration,migrate,expand,storage manager',
      youtube_ref: 'tcGIYGr4guA',
      category: 'sophomore',
      publishedDate: '2016-08-25T22:01:25.000Z'
  },
  {
      watched: 39025,
      rank: 0,
      like: 125,
      dislike: 4,
      favoriteCount: 0,
      duration: 'PT4M48S',
      commentCount: 14,
      slug: 'how-to-exand-your-storage-by-adding-additional-hard-drives',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdd07',
      title: 'How to exand your storage by adding additional hard drives.',
      code_name: 'QNP221',
      desc: 'This video will cover how to expand your storage 1) expand storage pool when finished migration 2) expand storage as you go',
      keywords: 'storage manager',
      youtube_ref: 'JJGX5x0TeD0',
      category: 'sophomore',
      publishedDate: '2016-08-16T23:06:57.000Z'
  },
  {
      watched: 17729,
      rank: 0,
      like: 39,
      dislike: 15,
      favoriteCount: 0,
      duration: 'PT3M36S',
      commentCount: 11,
      slug: 'how-to-migrate-to-another-qnap-nas',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdd0f',
      title: 'How to migrate to another QNAP NAS',
      code_name: 'QNP220',
      desc: 'This video will cover how to migrate the data from a source NAS to a destination NAS',
      keywords: 'move,moving,data,info,transfer,files',
      youtube_ref: 'DzVa_Drma98',
      category: 'sophomore',
      publishedDate: '2016-06-30T19:16:49.000Z'
  },
  {
      watched: 2575,
      rank: 0,
      like: 10,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT2M40S',
      commentCount: 0,
      slug: 'install-an-app-in-app-center',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdcf5',
      title: 'Install an App in App Center',
      code_name: 'QNP166',
      desc: 'This video will show you how to search and install an app in QNAP\'s App Center.',
      keywords: 'new,app,add,application,center,install,download,online',
      youtube_ref: 'UoqjUZM8F94',
      category: 'freshman',
      publishedDate: '2016-06-22T22:06:34.000Z'
  },
  {
      watched: 2149,
      rank: 0,
      like: 6,
      dislike: 5,
      favoriteCount: 0,
      duration: 'PT3M42S',
      commentCount: 3,
      slug: 'configure-network-settings-(for-arm-based-models)',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdcf3',
      title: 'Configure network settings (For ARM-based models)',
      code_name: 'QNP131',
      desc: 'In this video, you will learn how to initiate network configuration settings on your NAS.',
      keywords: 'internet,network,wifi,setup,home,connection',
      youtube_ref: 'Pm8yzGOOSBg',
      category: 'freshman',
      publishedDate: '2016-06-10T22:19:42.000Z'
  },
  {
      watched: 16288,
      rank: 0,
      like: 26,
      dislike: 7,
      favoriteCount: 0,
      duration: 'PT2M54S',
      commentCount: 1,
      slug: 'remote-access-via-cloudlink',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdd03',
      title: 'Remote access via CloudLink',
      code_name: 'QNP208',
      desc: 'This video explains how to set QNAP CloudLink to remotely access your NAS. ',
      keywords: 'QNAP,Cloud,link,remote,cloud,cloudlink',
      youtube_ref: 'FwWJUTrjMUc',
      category: 'sophomore',
      publishedDate: '2016-06-10T18:02:01.000Z'
  },
  {
      watched: 2442,
      rank: 0,
      like: 8,
      dislike: 11,
      favoriteCount: 0,
      duration: 'PT1M36S',
      commentCount: 2,
      slug: 'restore-your-mac-from-nas',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdd04',
      title: 'Restore your Mac from NAS ',
      code_name: 'QNP215',
      desc: 'This video will cover the few and easy steps on how to back up your files from your PC to your QNAP NAS.',
      keywords: 'Apple,Macbook,pro,OSX,Time,Machine,backup',
      youtube_ref: 'VcFUcnwzzpM',
      category: 'sophomore',
      publishedDate: '2016-06-07T23:28:50.000Z'
  },
  {
      watched: 3764,
      rank: 0,
      like: 9,
      dislike: 4,
      favoriteCount: 0,
      duration: 'PT1M51S',
      commentCount: 1,
      slug: 'set-up-network-access-protection',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdd02',
      title: 'Set up network access protection',
      code_name: 'QNP203',
      desc: 'This video will explain the importance of setting up protection for your network access and the steps involved to set it.',
      keywords: 'protection,safe,security,network,internet,protection',
      youtube_ref: '6ZZSVkW7nAw',
      category: 'sophomore',
      publishedDate: '2016-06-07T19:31:45.000Z'
  },
  {
      watched: 3297,
      rank: 0,
      like: 6,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT2M39S',
      commentCount: 0,
      slug: 'set-up-user-quota',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdcf4',
      title: 'Set Up User Quota',
      code_name: 'QNP164',
      desc: 'This video will cover how to setup user quota, and how it works.',
      keywords: 'limit,quota',
      youtube_ref: 'sGHBpHKLWSc',
      category: 'freshman',
      publishedDate: '2016-06-07T00:01:30.000Z'
  },
  {
      watched: 24478,
      rank: 0,
      like: 36,
      dislike: 14,
      favoriteCount: 0,
      duration: 'PT2M29S',
      commentCount: 2,
      slug: 'setup-myqnapcloud',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdd01',
      title: 'Setup myQNAPcloud',
      code_name: 'QNP201',
      desc: 'This video will take you through the steps on how to set up the myQNAPcloud feature. ',
      keywords: 'setup,start,myqnapcloud,cloud,begin,first',
      youtube_ref: 'ShnVe3QReRk',
      category: 'sophomore',
      publishedDate: '2016-06-06T23:32:23.000Z'
  },
  {
      watched: 2654,
      rank: 0,
      like: 8,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT2M27S',
      commentCount: 1,
      slug: 'set-up-system-notification',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdcf9',
      title: 'Set up system notification',
      code_name: 'QNP169',
      desc: 'This video will take you step by step on how to initialize the different system notifications options.',
      keywords: 'alert,notification,reminder,setup,notify,annouce,tell,inform,info',
      youtube_ref: 'yLlqB3L7I-M',
      category: 'freshman',
      publishedDate: '2016-06-06T22:19:11.000Z'
  },
  {
      watched: 8488,
      rank: 0,
      like: 39,
      dislike: 1,
      favoriteCount: 0,
      duration: 'PT3M14S',
      commentCount: 5,
      slug: 'backup-your-mac-to-nas',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdd06',
      title: 'Backup Your Mac to NAS',
      code_name: 'QNP214',
      desc: 'This video will cover the few and easy steps on how to back up your files from your Mac to your QNAP NAS.',
      keywords: 'Apple,Macbook,pro,OSX,TimeMachine,Restore',
      youtube_ref: 'KQRW27fou_c',
      category: 'sophomore',
      publishedDate: '2016-04-20T21:01:34.000Z'
  },
  {
      watched: 3079,
      rank: 0,
      like: 15,
      dislike: 1,
      favoriteCount: 0,
      duration: 'PT2M51S',
      commentCount: 0,
      slug: 'understand-your-nas-system',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdcf8',
      title: 'Understand your NAS system',
      code_name: 'QNP168',
      desc: 'In this video, you will learn how to navigate through the dashboard and user interface features on your NAS.',
      keywords: 'Dashboard,status,bandwidth,CPU,memory',
      youtube_ref: '0RCDcQbTko0',
      category: 'freshman',
      publishedDate: '2016-04-20T21:01:13.000Z'
  },
  {
      watched: 4337,
      rank: 0,
      like: 13,
      dislike: 3,
      favoriteCount: 0,
      duration: 'PT1M20S',
      commentCount: 5,
      slug: 'hardware-installation-ii',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdcf0',
      title: 'Hardware Installation II',
      code_name: 'QNP102',
      desc: 'Learn how to connect and power up your QNAP NAS.',
      keywords: 'initialize,cable,wiring,wire,router,power',
      youtube_ref: 'q9C53P6kuDY',
      category: 'freshman',
      publishedDate: '2016-03-04T00:29:00.000Z'
  },
  {
      watched: 7812,
      rank: 0,
      like: 12,
      dislike: 7,
      favoriteCount: 0,
      duration: 'PT2M55S',
      commentCount: 1,
      slug: 'set-up-folder-permission',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdcf2',
      title: 'Set up folder permission',
      code_name: 'QNP122',
      desc: 'In this video, you will learn how to allow and restrict user access for your files on your NAS.',
      keywords: 'user,group,create,share,folder,rw,ro,deny,admin,privilege,account',
      youtube_ref: '32P8Qu0Nr7A',
      category: 'freshman',
      publishedDate: '2016-02-26T00:57:36.000Z'
  },
  {
      watched: 5211,
      rank: 0,
      like: 12,
      dislike: 2,
      favoriteCount: 0,
      duration: 'PT3M',
      commentCount: 1,
      slug: 'set-up-group-permission',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdcf1',
      title: 'Set up group permission',
      code_name: 'QNP121',
      desc: 'This video shows you how to create user group and set permission for each group for your NAS.',
      keywords: 'user,group,create,share,folder,rw,ro,deny,admin,privilege,account',
      youtube_ref: 'hlu7Y91P1NI',
      category: 'freshman',
      publishedDate: '2016-02-26T00:57:26.000Z'
  },
  {
      watched: 15429,
      rank: 0,
      like: 31,
      dislike: 2,
      favoriteCount: 0,
      duration: 'PT2M19S',
      commentCount: 0,
      slug: 'set-up-user-permission',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdcff',
      title: 'Set up user permission',
      code_name: 'QNP120',
      desc: 'This video shows you how to asign user permission and access for other users on your NAS.',
      keywords: 'user,group,create,share,folder,rw,ro,deny,admin,privilege,account',
      youtube_ref: 'KtUma6NmKQs',
      category: 'freshman',
      publishedDate: '2016-02-26T00:56:14.000Z'
  },
  {
      watched: 2821,
      rank: 0,
      like: 5,
      dislike: 0,
      favoriteCount: 0,
      duration: 'PT1M54S',
      commentCount: 0,
      slug: 'how-to-use-qsirch',
      slide_link: '',
      comments: [],
      _id: '5ca2ac1289b0a25980f7a8b3',
      publishedDate: '2016-02-18T03:41:06.000Z',
      keywords: 'full context,search',
      desc: 'This tutorial teaches how to do a full context search on QNAP NAS',
      category: 'sophomore',
      youtube_ref: 'OrkpWCGRCgg',
      code_name: 'QNP219',
      title: 'How to use Qsirch',
      __v: 0
  },
  {
      watched: 18470,
      rank: 0,
      like: 64,
      dislike: 12,
      favoriteCount: 0,
      duration: 'PT22M30S',
      commentCount: 7,
      slug: 'your-ultimate-multimedia-server-plex-on-qnap-nas',
      slide_link: '',
      comments: [],
      _id: '5bbb9ea3610dbf576488a9ed',
      publishedDate: '2016-01-25T21:04:06.000Z',
      keywords: 'Plex',
      desc: 'Introduction of how to use Plex on QNAP NAS, and the guide of how to choose a QNAP for Plex',
      category: 'webinar',
      youtube_ref: '9ixFpY9tysc',
      code_name: 'Webinar9',
      title: 'Your Ultimate Multimedia Server - Plex on QNAP NAS',
      __v: 0
  },
  {
      watched: 30233,
      rank: 0,
      like: 40,
      dislike: 3,
      favoriteCount: 0,
      duration: 'PT2M10S',
      commentCount: 5,
      slug: 'how-to-get-started-with-hd-station',
      slide_link: '',
      comments: [],
      _id: '5ca2ad4389b0a25980f7a8c5',
      publishedDate: '2015-11-26T08:48:56.000Z',
      keywords: 'Local Display',
      desc: 'Enable HD station and watch movie directly from QNAP NAS.',
      category: 'sophomore',
      youtube_ref: 'XRJF0gKIHAk',
      code_name: 'QNP216',
      title: 'How to get started with HD Station',
      __v: 0
  },
  {
      watched: 21710,
      rank: 0,
      like: 45,
      dislike: 12,
      favoriteCount: 0,
      duration: 'PT38M59S',
      commentCount: 4,
      slug: 'introduction-of-qsync-central-station-2.0',
      slide_link: '',
      comments: [],
      _id: '5bbb9e35610dbf576488a9eb',
      publishedDate: '2015-11-20T00:45:58.000Z',
      keywords: 'Qsync Central,Dropbox',
      desc: 'The detail demostration of QNAP new Qsync Centeral Station 2.0 on QTS 4.2',
      category: 'webinar',
      youtube_ref: 'dIe5o3FvPbM',
      code_name: 'Webinar8',
      title: 'Introduction of Qsync Central Station 2.0',
      __v: 0
  },
  {
      watched: 9008,
      rank: 0,
      like: 65,
      dislike: 1,
      favoriteCount: 0,
      duration: 'PT3M25S',
      commentCount: 3,
      slug: 'transfer-files-from-mac',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdcfb',
      title: 'Transfer files from Mac',
      code_name: 'QNP111',
      desc: 'This video will cover the few and easy steps on how to transfer your files from a Mac to your QNAP NAS.',
      keywords: 'afp,nfs,smb,samba,apple,osx,qfinder',
      youtube_ref: '4LPAZowbh78',
      category: 'freshman',
      publishedDate: '2015-07-09T21:29:09.000Z'
  },
  {
      watched: 13412,
      rank: 0,
      like: 32,
      dislike: 3,
      favoriteCount: 0,
      duration: 'PT7M21S',
      commentCount: 6,
      slug: 'initialize-your-nas-system',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdcfc',
      title: 'Initialize your NAS system',
      code_name: 'QNP103',
      desc: 'Learn how to boot up your QNAP NAS and get started.',
      keywords: 'configurate,qfinder,cloud,installation,local,key,network,hostname,ip,address,timezone,raid,configuration',
      youtube_ref: 'wMKM-RYJKFc',
      category: 'freshman',
      publishedDate: '2015-07-09T18:50:11.000Z'
  },
  {
      watched: 36203,
      rank: 0,
      like: 48,
      dislike: 2,
      favoriteCount: 0,
      duration: 'PT3M1S',
      commentCount: 6,
      slug: 'transfer-files-via-file-station',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdcfd',
      title: 'Transfer files via File Station',
      code_name: 'QNP113',
      desc: 'This video will cover transfer files to and from your NAS using the File Station feature.',
      keywords: 'cross,browser,platform,chrome,firefox,ie,qfinder,ip,address,find',
      youtube_ref: 'hsJwegPlJWk',
      category: 'freshman',
      publishedDate: '2015-07-08T01:12:14.000Z'
  },
  {
      watched: 26770,
      rank: 0,
      like: 74,
      dislike: 8,
      favoriteCount: 0,
      duration: 'PT2M29S',
      commentCount: 10,
      slug: 'transfer-files-from-windows',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdcef',
      title: 'Transfer files from Windows',
      code_name: 'QNP110',
      desc: 'In this video, we will teach you about the few and easy steps on how to transfer your files from your PC to your QNAP NAS.',
      keywords: 'samba,smb,qfinder,ip,address,find',
      youtube_ref: 'J5yhBpsPSFU',
      category: 'freshman',
      publishedDate: '2015-06-24T17:47:04.000Z'
  },
  {
      watched: 8592,
      rank: 0,
      like: 24,
      dislike: 1,
      favoriteCount: 0,
      duration: 'PT2M59S',
      commentCount: 1,
      slug: 'hardware-installation-i',
      slide_link: '',
      comments: [],
      _id: '5a386ecb7c59c84a439cdd00',
      title: 'Hardware Installation I',
      code_name: 'QNP101',
      desc: 'How to install hard drives onto your QNAP NAS.',
      keywords: 'initialize,hdd,openbox',
      youtube_ref: 'kwBQ5ev20qo',
      category: 'freshman',
      publishedDate: '2015-06-24T00:13:45.000Z'
  },
  {
      watched: 53228,
      rank: 0,
      like: 194,
      dislike: 37,
      favoriteCount: 0,
      duration: 'PT27M2S',
      commentCount: 29,
      slug: 'get-the-most-from-your-mac-with-a-qnap-turbo-nas',
      slide_link: '',
      comments: [],
      _id: '5bbb9dc8610dbf576488a9e9',
      publishedDate: '2014-12-11T16:18:47.000Z',
      keywords: 'Apple,Mac,OSX',
      desc: 'You can easily to store, download, share, and backup your data from your Mac to your QNAP NAS along with MUCH more!',
      category: 'webinar',
      youtube_ref: 'dJJr_XSrOao',
      code_name: 'Webinar7',
      title: 'Get the Most From your Mac with a QNAP Turbo NAS',
      __v: 0
  }
]